// src/components/ProjectAnalysisResult.jsx
import React from 'react';

export default function ProjectAnalysisResult({ 
  data, 
  onRegenerate, 
  onEdit, 
  isGenerating = false,
  generationError = null 
}) {
  if (!data) return null;

  const {
    project = {},
    stats = {},
    flags = {},
    aiDescription = '',
  } = data;

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* 1. Project Header */}
      <div className="bg-slate-800/60 border border-slate-700/60 rounded-3xl p-6 sm:p-8 space-y-6 shadow-xl">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            {project.ownerAvatar && (
              <img
                src={project.ownerAvatar}
                alt={project.owner || 'Owner'}
                className="w-16 h-16 rounded-2xl border-2 border-indigo-500/40 shadow-md"
              />
            )}
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-2xl font-extrabold text-white">
                  {project.name || 'Untitled Project'}
                </h2>
                {flags?.isFork && (
                  <span className="px-2 py-0.5 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400 text-xs font-semibold">
                    Fork
                  </span>
                )}
              </div>
              <p className="text-sm text-slate-400 font-medium">
                by <span className="text-indigo-400">@{project.owner || 'unknown'}</span>
              </p>
            </div>
          </div>

          {project.htmlUrl && (
            <a
              href={project.htmlUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="bg-indigo-600 hover:bg-indigo-500 text-white font-medium px-4 py-2 rounded-xl text-sm transition shadow-lg shadow-indigo-600/30"
            >
              View on GitHub ↗
            </a>
          )}
        </div>

        {/* 2. AI Project Description Section */}
        <div className="border-t border-slate-700/40 pt-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-400 flex items-center gap-2">
              <span>✨</span> AI Project Description
            </h3>
            <span className="text-xs text-slate-500">Generated by DevSphere AI</span>
          </div>

          {/* Conditional Rendering logic */}
          {isGenerating ? (
            <div className="p-4 bg-slate-900/50 rounded-2xl border border-slate-700/40 text-slate-400 text-sm animate-pulse">
              Generating project description with AI...
            </div>
          ) : generationError ? (
            <div className="p-4 bg-rose-500/10 border border-rose-500/20 rounded-2xl text-rose-400 text-sm flex items-center justify-between">
              <span>⚠️ {generationError}</span>
              <button
                onClick={onRegenerate}
                className="px-3 py-1 bg-rose-500/20 hover:bg-rose-500/30 text-rose-300 rounded-lg text-xs font-semibold transition"
              >
                Try Again
              </button>
            </div>
          ) : (
            <div className="p-5 bg-slate-900/60 rounded-2xl border border-slate-700/50 text-slate-300 text-base leading-relaxed">
              {aiDescription || project.description || 'No description available.'}
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex items-center gap-3 pt-2">
            <button
              onClick={onRegenerate}
              disabled={isGenerating}
              className="px-4 py-2 bg-slate-700 hover:bg-slate-600 disabled:opacity-50 text-white rounded-xl text-sm font-medium transition cursor-pointer"
            >
              {isGenerating ? 'Generating...' : '🔄 Regenerate'}
            </button>
            {onEdit && (
              <button
                onClick={onEdit}
                className="px-4 py-2 bg-slate-700/50 hover:bg-slate-700 text-slate-300 rounded-xl text-sm font-medium transition cursor-pointer"
              >
                ✏️ Edit
              </button>
            )}
          </div>
        </div>
      </div>

      {/* 3. Project Statistics Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-slate-800/40 border border-slate-700/60 rounded-2xl p-4 text-center">
          <div className="text-xs text-slate-400 font-medium">⭐ Stars</div>
          <div className="text-2xl font-extrabold text-amber-400 mt-1">{stats?.stars ?? 0}</div>
        </div>
        <div className="bg-slate-800/40 border border-slate-700/60 rounded-2xl p-4 text-center">
          <div className="text-xs text-slate-400 font-medium">🍴 Forks</div>
          <div className="text-2xl font-extrabold text-cyan-400 mt-1">{stats?.forks ?? 0}</div>
        </div>
        <div className="bg-slate-800/40 border border-slate-700/60 rounded-2xl p-4 text-center">
          <div className="text-xs text-slate-400 font-medium">👁 Watchers</div>
          <div className="text-2xl font-extrabold text-purple-400 mt-1">{stats?.watchers ?? 0}</div>
        </div>
        <div className="bg-slate-800/40 border border-slate-700/60 rounded-2xl p-4 text-center">
          <div className="text-xs text-slate-400 font-medium">⚠️ Open Issues</div>
          <div className="text-2xl font-extrabold text-rose-400 mt-1">{stats?.openIssues ?? 0}</div>
        </div>
      </div>
    </div>
  );
}